---
# tasks file for prepare-ubuntu
- name: update cache
  apt:
    update_cache: yes
- name: install required packages
  apt:
    pkg:
      - nginx
      - docker.io
      - git
      - curl
      - python3
      - python3-pip
    state: latest

- name: enable docker service
  service:
    name: docker
    state: started
    enabled: yes
- name: install docker-compose
  pip:
    name: docker-compose
- name: enable nginx service
  service:
    name: nginx
    state: started
    enabled: yes
- name: Log into DockerHub
  docker_login:
    username: "{{DOCKER_USERNAME}}"
    password: "{{DOCKER_PASS}}"

